# Generated by Django 4.2.2 on 2023-07-27 18:37

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким никнеймом уже существует.'}, help_text='Обязательное поле. Максимум 150 символов.Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[user.validators.UnicodeUsernameValidator()], verbose_name='Никнейм'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='uq_user_author'),
        ),
    ]
